<!DOCTYPE html>
<html lang="en">

<head>
    <title>Scholarship Reports</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('css/table.css') }}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    @include('partials._pageheader')
    <x-alert />
    <div class="ctnmain">
        <div class="container-fluid rounded border border-success py-2 shadow-sm">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto my-2">
                    <span class="fw-bold text-success h2">Scholarship Reports</span>
                </div>
                <div class="col-auto my-2">
                    <button class="btn btn-success text-white px-4 py-2" data-bs-toggle="modal"
                        data-bs-target="#reportModal">
                        <i class="fas fa-chart-line me-2"></i> Generate Summary Report
                    </button>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row align-items-center my-2">
                <div class="col-auto" style="margin-left: auto">
                    <div class="row gx-1 align-items-center">
                        <div class="" style="width: max-content">
                            <button class="reportfilter btn btn-sm btn-success w-100" id="toggleAllReports">All</button>
                        </div>
                        <div class="" style="width: max-content">
                            <button class="reportfilter btn btn-sm btn-outline-success w-100"
                                id="toggleCollegeReports">College</button>
                        </div>
                        <div class="" style="width: max-content">
                            <button class="reportfilter btn btn-sm btn-outline-success w-100"
                                id="toggleSHSReports">Senior High</button>
                        </div>
                        <div class="" style="width: max-content">
                            <button class="reportfilter btn btn-sm btn-outline-success w-100"
                                id="toggleJHSReports">Junior High</button>
                        </div>
                        <div class="" style="width: max-content">
                            <button class="reportfilter btn btn-sm btn-outline-success w-100"
                                id="toggleElemReports">Elementary</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ctnreport" id="allReports">
                <div class="ctntable table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="text-center align-middle">#</th>
                                <th class="text-center align-middle">Report Name</th>
                                <th class="text-center align-middle">School Level</th>
                                <th class="text-center align-middle">Date Scope</th>
                                <th class="text-center align-middle">Date Generated</th>
                                <th class="text-center align-middle">Generated By</th>
                                <th class="text-center align-middle">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($reports['All'] as $index => $report)
                                <tr class="report-row" data-schoollevel="{{ $report->schoollevel }}">
                                    <td class="text-center align-middle">{{ $index + 1 }}</td>
                                    <td class="text-center align-middle">
                                        {{ $report->reportname ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">{{ $report->level ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->datescope ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ Carbon\Carbon::parse($report->dategenerated)->format('F j, Y') ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->generatedby ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        <button class="btn btn-sm btn-success view-report" data-bs-toggle="modal"
                                            data-bs-target="#fileModal-{{ $report->id }}">
                                            <i class="fas fa-eye"></i>
                                        </button>
                                        <button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                    </td>
                                </tr>

                                <div class="modal fade" id="fileModal-{{ $report->id }}" tabindex="-1"
                                    aria-labelledby="fileModalLabel-{{ $report->id }}" aria-hidden="true">
                                    <div class="modal-dialog modal-xl" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header bg-success text-white">
                                                <h5 class="modal-title" id="fileModalLabel-{{ $report->id }}">Report
                                                    Preview</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <iframe id="reportIframe"
                                                    src="{{ url('storage/' . $report->filepath) }}"
                                                    style="width: 100%; height: 80vh;" frameborder="0">
                                                    Your browser does not support iframes. Please download the PDF file
                                                    <a href="{{ url('storage/' . $report->filepath) }}" target="_blank"
                                                        download>click here</a>.
                                                </iframe>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <tr>
                                    <td class="text-center align-middle" colspan="7">No Reports Found.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <!-- Pagination Controls -->
                <div class="d-flex justify-content-center mt-3">
                    {{ $reports['All']->links('pagination::bootstrap-4') }}
                </div>
            </div>
            <div class="ctnreport" id="collegeReports" style="display: none">
                <div class="ctntable table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="text-center align-middle">#</th>
                                <th class="text-center align-middle">Report Name</th>
                                <th class="text-center align-middle">School Level</th>
                                <th class="text-center align-middle">Date Scope</th>
                                <th class="text-center align-middle">Date Generated</th>
                                <th class="text-center align-middle">Generated By</th>
                                <th class="text-center align-middle">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($reports['College'] as $index => $report)
                                <tr class="report-row" data-schoollevel="{{ $report->schoollevel }}">
                                    <td class="text-center align-middle">{{ $index + 1 }}</td>
                                    <td class="text-center align-middle">
                                        {{ $report->reportname ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">{{ $report->level ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->datescope ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ Carbon\Carbon::parse($report->dategenerated)->format('F j, Y') ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->generatedby ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        <button class="btn btn-sm btn-success view-report" data-bs-toggle="modal"
                                            data-bs-target="#fileModal-{{ $report->id }}">
                                            <i class="fas fa-eye"></i>
                                        </button>
                                        <button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                    </td>
                                </tr>

                                <div class="modal fade" id="fileModal-{{ $report->id }}" tabindex="-1"
                                    aria-labelledby="fileModalLabel-{{ $report->id }}" aria-hidden="true">
                                    <div class="modal-dialog modal-xl" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header bg-success text-white">
                                                <h5 class="modal-title" id="fileModalLabel-{{ $report->id }}">
                                                    Report
                                                    Preview</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <iframe id="reportIframe"
                                                    src="{{ url('storage/' . $report->filepath) }}"
                                                    style="width: 100%; height: 80vh;" frameborder="0">
                                                    Your browser does not support iframes. Please download the PDF file
                                                    <a href="{{ url('storage/' . $report->filepath) }}"
                                                        target="_blank" download>click here</a>.
                                                </iframe>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <tr>
                                    <td class="text-center align-middle" colspan="7">No Reports Found.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <!-- Pagination Controls -->
                <div class="d-flex justify-content-center mt-3">
                    {{ $reports['College']->links('pagination::bootstrap-4') }}
                </div>
            </div>
            <div class="ctnreport" id="shsReports" style="display: none">
                <div class="ctntable table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="text-center align-middle">#</th>
                                <th class="text-center align-middle">Report Name</th>
                                <th class="text-center align-middle">School Level</th>
                                <th class="text-center align-middle">Date Scope</th>
                                <th class="text-center align-middle">Date Generated</th>
                                <th class="text-center align-middle">Generated By</th>
                                <th class="text-center align-middle">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($reports['Senior High'] as $index => $report)
                                <tr class="report-row" data-schoollevel="{{ $report->schoollevel }}">
                                    <td class="text-center align-middle">{{ $index + 1 }}</td>
                                    <td class="text-center align-middle">
                                        {{ $report->reportname ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">{{ $report->level ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->datescope ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ Carbon\Carbon::parse($report->dategenerated)->format('F j, Y') ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->generatedby ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        <button class="btn btn-sm btn-success view-report" data-bs-toggle="modal"
                                            data-bs-target="#fileModal-{{ $report->id }}">
                                            <i class="fas fa-eye"></i>
                                        </button>
                                        <button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                    </td>
                                </tr>

                                <div class="modal fade" id="fileModal-{{ $report->id }}" tabindex="-1"
                                    aria-labelledby="fileModalLabel-{{ $report->id }}" aria-hidden="true">
                                    <div class="modal-dialog modal-xl" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header bg-success text-white">
                                                <h5 class="modal-title" id="fileModalLabel-{{ $report->id }}">
                                                    Report
                                                    Preview</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <iframe id="reportIframe"
                                                    src="{{ url('storage/' . $report->filepath) }}"
                                                    style="width: 100%; height: 80vh;" frameborder="0">
                                                    Your browser does not support iframes. Please download the PDF file
                                                    <a href="{{ url('storage/' . $report->filepath) }}"
                                                        target="_blank" download>click here</a>.
                                                </iframe>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <tr>
                                    <td class="text-center align-middle" colspan="7">No Reports Found.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <!-- Pagination Controls -->
                <div class="d-flex justify-content-center mt-3">
                    {{ $reports['Senior High']->links('pagination::bootstrap-4') }}
                </div>
            </div>
            <div class="ctnreport" id="jhsReports" style="display: none">
                <div class="ctntable table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="text-center align-middle">#</th>
                                <th class="text-center align-middle">Report Name</th>
                                <th class="text-center align-middle">School Level</th>
                                <th class="text-center align-middle">Date Scope</th>
                                <th class="text-center align-middle">Date Generated</th>
                                <th class="text-center align-middle">Generated By</th>
                                <th class="text-center align-middle">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($reports['Junior High'] as $index => $report)
                                <tr class="report-row" data-schoollevel="{{ $report->schoollevel }}">
                                    <td class="text-center align-middle">{{ $index + 1 }}</td>
                                    <td class="text-center align-middle">
                                        {{ $report->reportname ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">{{ $report->level ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->datescope ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ Carbon\Carbon::parse($report->dategenerated)->format('F j, Y') ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->generatedby ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        <button class="btn btn-sm btn-success view-report" data-bs-toggle="modal"
                                            data-bs-target="#fileModal-{{ $report->id }}">
                                            <i class="fas fa-eye"></i>
                                        </button>
                                        <button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                    </td>
                                </tr>

                                <div class="modal fade" id="fileModal-{{ $report->id }}" tabindex="-1"
                                    aria-labelledby="fileModalLabel-{{ $report->id }}" aria-hidden="true">
                                    <div class="modal-dialog modal-xl" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header bg-success text-white">
                                                <h5 class="modal-title" id="fileModalLabel-{{ $report->id }}">
                                                    Report
                                                    Preview</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <iframe id="reportIframe"
                                                    src="{{ url('storage/' . $report->filepath) }}"
                                                    style="width: 100%; height: 80vh;" frameborder="0">
                                                    Your browser does not support iframes. Please download the PDF file
                                                    <a href="{{ url('storage/' . $report->filepath) }}"
                                                        target="_blank" download>click here</a>.
                                                </iframe>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <tr>
                                    <td class="text-center align-middle" colspan="7">No Reports Found.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <!-- Pagination Controls -->
                <div class="d-flex justify-content-center mt-3">
                    {{ $reports['Junior High']->links('pagination::bootstrap-4') }}
                </div>
            </div>
            <div class="ctnreport" id="elemReports" style="display: none">
                <div class="ctntable table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="text-center align-middle">#</th>
                                <th class="text-center align-middle">Report Name</th>
                                <th class="text-center align-middle">School Level</th>
                                <th class="text-center align-middle">Date Scope</th>
                                <th class="text-center align-middle">Date Generated</th>
                                <th class="text-center align-middle">Generated By</th>
                                <th class="text-center align-middle">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($reports['Elementary'] as $index => $report)
                                <tr class="report-row" data-schoollevel="{{ $report->schoollevel }}">
                                    <td class="text-center align-middle">{{ $index + 1 }}</td>
                                    <td class="text-center align-middle">
                                        {{ $report->reportname ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">{{ $report->level ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->datescope ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ Carbon\Carbon::parse($report->dategenerated)->format('F j, Y') ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        {{ $report->generatedby ?? 'Failed to load data' }}
                                    </td>
                                    <td class="text-center align-middle">
                                        <button class="btn btn-sm btn-success view-report" data-bs-toggle="modal"
                                            data-bs-target="#fileModal-{{ $report->id }}">
                                            <i class="fas fa-eye"></i>
                                        </button>
                                        <button class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                    </td>
                                </tr>

                                <div class="modal fade" id="fileModal-{{ $report->id }}" tabindex="-1"
                                    aria-labelledby="fileModalLabel-{{ $report->id }}" aria-hidden="true">
                                    <div class="modal-dialog modal-xl" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header bg-success text-white">
                                                <h5 class="modal-title" id="fileModalLabel-{{ $report->id }}">
                                                    Report
                                                    Preview</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <iframe id="reportIframe"
                                                    src="{{ url('storage/' . $report->filepath) }}"
                                                    style="width: 100%; height: 80vh;" frameborder="0">
                                                    Your browser does not support iframes. Please download the PDF file
                                                    <a href="{{ url('storage/' . $report->filepath) }}"
                                                        target="_blank" download>click here</a>.
                                                </iframe>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @empty
                                <tr>
                                    <td class="text-center align-middle" colspan="7">No Reports Found.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <!-- Pagination Controls -->
                <div class="d-flex justify-content-center mt-3">
                    {{ $reports['Elementary']->links('pagination::bootstrap-4') }}
                </div>
            </div>
        </div>

        <div class="container-fluid rounded border border-success py-2 shadow-sm">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto my-2">
                    <span class="fw-bold text-success h2">Scholars Performance Summary</span>
                </div>
                <div class="col-auto my-2">
                    <a class="btn btn-success text-white px-4 py-2" id="perfSummary"
                        href="{{ route('evaluatescholars') }}">
                        <i class="fas fa-chart-line me-2"></i>Generate
                        Performance Summary</a>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto">
                    <span class="fw-bold text-success h4 text-center">A.Y. {{ $acadyear }}</span>
                </div>
                <div class="col-auto">
                    <div class="row gx-1 align-items-center">
                        <div class="" style="width: max-content">
                            <button class="filter btn btn-sm btn-success w-100" id="toggleCollege">College</button>
                        </div>
                        <div class="" style="width: max-content">
                            <button class="filter btn btn-sm btn-outline-success w-100" id="toggleSHS">Senior
                                High</button>
                        </div>
                        <div class="" style="width: max-content">
                            <button class="filter btn btn-sm btn-outline-success w-100" id="toggleJHS">Junior
                                High</button>
                        </div>
                        <div class="" style="width: max-content">
                            <button class="filter btn btn-sm btn-outline-success w-100"
                                id="toggleElem">Elementary</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ctn" id="college">
                @php
                    $cycles = [
                        'Semester' => ['columns' => ['1st Sem GWA', '2nd Sem GWA']],
                        'Trimester' => ['columns' => ['1st Sem GWA', '2nd Sem GWA', '3rd Sem GWA']],
                    ];
                @endphp
                @if ($colleges->isEmpty())
                    <div class="row text-center fw-bold h6">
                        <span>No Data Available</span>
                    </div>
                @endif
                @foreach ($cycles as $cycle => $data)
                    @php $cycleResults = $colleges->filter(fn($result) => $result->acadcycle == $cycle); @endphp

                    @if (!$cycleResults->isEmpty())
                        <div class="row">
                            <span class="fw-bold text-success h4 text-center">Academic Cycle:
                                {{ $cycle }}</span>
                        </div>
                        <div class="ctntable table-responsive">
                            <table class="table table-bordered">
                                <thead class="">
                                    <tr>
                                        <th class="text-center align-middle">#</th>
                                        <th class="text-center align-middle">Scholar Name</th>
                                        @foreach ($data['columns'] as $column)
                                            <th class="text-center align-middle">{{ $column }}</th>
                                        @endforeach
                                        <th class="text-center align-middle">Rendered CS Hours</th>
                                        <th class="text-center align-middle">HC Absent Count</th>
                                        <th class="text-center align-middle">Penalty Count</th>
                                        <th class="text-center align-middle">Scholarship Status</th>
                                        <th class="text-center align-middle">Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $index = 1; @endphp
                                    @foreach ($cycleResults as $result)
                                        <tr>
                                            <td class="text-center align-middle">{{ $index++ }}</td>
                                            <td class="text-center align-middle">{{ $result->basicInfo->scLastname }},
                                                {{ $result->basicInfo->scFirstname }}
                                                {{ $result->basicInfo->scMiddlename }}
                                            </td>
                                            @foreach ($data['columns'] as $key => $column)
                                                <td class="text-center align-middle">
                                                    {{ $result->{'gwasem' . ($key + 1)} ?? 'No Data' }}
                                                </td>
                                            @endforeach
                                            <td class="text-center align-middle">{{ $result->cshours ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->hcabsentcount ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->penaltycount ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->scholarshipinfo->scholarshipstatus ?? '' }}</td>
                                            <td class="text-center align-middle">
                                                {{ $result->remark ?? 'Incomplete Data' }}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif
                @endforeach
            </div>
            <div class="ctn" id="shs" style="display: none;">
                @php
                    $cycles = [
                        'Semester' => ['columns' => ['1st Sem GWA', '2nd Sem GWA']],
                        'Trimester' => ['columns' => ['1st Sem GWA', '2nd Sem GWA', '3rd Sem GWA']],
                    ];
                @endphp
                @if ($shs->isEmpty())
                    <div class="row text-center fw-bold h6">
                        <span>No Data Available</span>
                    </div>
                @endif
                @foreach ($cycles as $cycle => $data)
                    @php $cycleResults = $shs->filter(fn($result) => $result->acadcycle == $cycle); @endphp

                    @if (!$cycleResults->isEmpty())
                        <div class="row">
                            <span class="fw-bold text-success h4 text-center">Academic Cycle:
                                {{ $cycle }}</span>
                        </div>
                        <div class="ctntable table-responsive">
                            <table class="table table-bordered">
                                <thead class="">
                                    <tr>
                                        <th class="text-center align-middle">#</th>
                                        <th class="text-center align-middle">Scholar Name</th>
                                        @foreach ($data['columns'] as $column)
                                            <th class="text-center align-middle">{{ $column }}</th>
                                        @endforeach
                                        <th class="text-center align-middle">HC Absent Count</th>
                                        <th class="text-center align-middle">Penalty Count</th>
                                        <th class="text-center align-middle">Scholarship Status</th>
                                        <th class="text-center align-middle">Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $index = 1; @endphp
                                    @foreach ($cycleResults as $result)
                                        <tr>
                                            <td class="text-center align-middle">{{ $index++ }}</td>
                                            <td class="text-center align-middle">{{ $result->basicInfo->scLastname }},
                                                {{ $result->basicInfo->scFirstname }}
                                                {{ $result->basicInfo->scMiddlename }}
                                            </td>
                                            @foreach ($data['columns'] as $key => $column)
                                                <td class="text-center align-middle">
                                                    {{ $result->{'gwasem' . ($key + 1)} ?? 'No Data' }}
                                                </td>
                                            @endforeach
                                            <td class="text-center align-middle">
                                                {{ $result->hcabsentcount ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->penaltycount ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->scholarshipinfo->scholarshipstatus ?? '' }}</td>
                                            <td class="text-center align-middle">
                                                {{ $result->remark ?? 'Incomplete Data' }}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif
                @endforeach
            </div>
            <div class="ctn" id="jhs" style="display: none;">
                @php
                    $cycles = [
                        'Quarter' => [
                            'columns' => ['1st Quarter GWA', '2nd Quarter GWA', '3rd Quarter GWA', '4th Quarter GWA'],
                        ],
                    ];
                @endphp
                @if ($jhs->isEmpty())
                    <div class="row text-center fw-bold h6">
                        <span>No Data Available</span>
                    </div>
                @endif
                @foreach ($cycles as $cycle => $data)
                    @php $cycleResults = $jhs->filter(fn($result) => $result->acadcycle == $cycle); @endphp

                    @if (!$cycleResults->isEmpty())
                        <div class="row">
                            <span class="fw-bold text-success h4 text-center">Academic Cycle:
                                {{ $cycle }}</span>
                        </div>
                        <div class="ctntable table-responsive">
                            <table class="table table-bordered">
                                <thead class="">
                                    <tr>
                                        <th class="text-center align-middle">#</th>
                                        <th class="text-center align-middle">Scholar Name</th>
                                        <th class="text-center align-middle">General Average</th>
                                        <th class="text-center align-middle">HC Absent Count</th>
                                        <th class="text-center align-middle">Penalty Count</th>
                                        <th class="text-center align-middle">Scholarship Status</th>
                                        <th class="text-center align-middle">Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $index = 1; @endphp
                                    @foreach ($cycleResults as $result)
                                        <tr>
                                            <td class="text-center align-middle">{{ $index++ }}</td>
                                            <td class="text-center align-middle">{{ $result->basicInfo->scLastname }},
                                                {{ $result->basicInfo->scFirstname }}
                                                {{ $result->basicInfo->scMiddlename }}
                                            </td>
                                            <td class="text-center align-middle">{{ $result->gwa ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->hcabsentcount ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->penaltycount ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->scholarshipinfo->scholarshipstatus ?? '' }}</td>
                                            <td class="text-center align-middle">
                                                {{ $result->remark ?? 'Incomplete Data' }}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif
                @endforeach
            </div>
            <div class="ctn" id="elem" style="display: none;">
                @php
                    $cycles = [
                        'Quarter' => [
                            'columns' => ['1st Quarter GWA', '2nd Quarter GWA', '3rd Quarter GWA', '4th Quarter GWA'],
                        ],
                    ];
                @endphp
                @if ($elem->isEmpty())
                    <div class="row text-center fw-bold h6">
                        <span>No Data Available</span>
                    </div>
                @endif
                @foreach ($cycles as $cycle => $data)
                    @php $cycleResults = $elem->filter(fn($result) => $result->acadcycle == $cycle); @endphp

                    @if (!$cycleResults->isEmpty())
                        <div class="row">
                            <span class="fw-bold text-success h4 text-center">Academic Cycle:
                                {{ $cycle }}</span>
                        </div>
                        <div class="ctntable table-responsive">
                            <table class="table table-bordered">
                                <thead class="">
                                    <tr>
                                        <th class="text-center align-middle">#</th>
                                        <th class="text-center align-middle">Scholar Name</th>
                                        <th class="text-center align-middle">General Average</th>
                                        <th class="text-center align-middle">HC Absent Count</th>
                                        <th class="text-center align-middle">Penalty Count</th>
                                        <th class="text-center align-middle">Scholarship Status</th>
                                        <th class="text-center align-middle">Remark</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $index = 1; @endphp
                                    @foreach ($cycleResults as $result)
                                        <tr>
                                            <td class="text-center align-middle">{{ $index++ }}</td>
                                            <td class="text-center align-middle">
                                                {{ $result->basicInfo->scLastname }},
                                                {{ $result->basicInfo->scFirstname }}
                                                {{ $result->basicInfo->scMiddlename }}
                                            </td>
                                            <td class="text-center align-middle">{{ $result->gwa ?? 'No Data' }}
                                            <td class="text-center align-middle">
                                                {{ $result->hcabsentcount ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->penaltycount ?? 'No Data' }}
                                            </td>
                                            <td class="text-center align-middle">
                                                {{ $result->scholarshipinfo->scholarshipstatus ?? '' }}</td>
                                            <td class="text-center align-middle">
                                                {{ $result->remark ?? 'Incomplete Data' }}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif
                @endforeach
            </div>
        </div>
    </div>

    <div class="modal fade" id="reportModal" tabindex="-1" aria-labelledby="reportModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post" action="{{ route('generateSummaryReport') }}" id="summaryReportForm">
                    @csrf
                    <div class="modal-header bg-success text-white">
                        <h5 class="modal-title" id="reportModalLabel">Generate Summary Report</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="mb-3 row align-items-center">
                            <div class="col-md-6">
                                <label for="schoollevel" class="form-label">School Level</label>
                            </div>
                            <div class="col-md-6">
                                <select name="schoollevel" id="schoollevel" class="form-select" required>
                                    <option value="All">All</option>
                                    <option value="College">College</option>
                                    <option value="Senior High">Senior High</option>
                                    <option value="Junior High">Junior High</option>
                                    <option value="Elementary">Elementary</option>
                                </select>
                            </div>
                        </div>
                        <div class="mb-3 row align-items-center">
                            <div class="col-md-6">
                                <label for="periodtype" class="form-label">Report Period</label>
                            </div>
                            <div class="col-md-6">
                                <select name="periodtype" id="periodtype" class="form-select" required>
                                    <option value="Annually">Annually</option>
                                    <option value="Quarterly">Quarterly</option>
                                    <option value="Monthly">Monthly</option>
                                </select>
                            </div>
                        </div>
                        <div class="mb-3 row align-items-center" id="periodduration" hidden>
                            <div class="col-md-6">
                                <label for="period" class="form-label">Date</label>
                            </div>
                            <div class="col-md-6">
                                <select name="period" id="period" class="form-select">
                                </select>
                            </div>
                        </div>
                        <div class="mb-3 row align-items-center" id="yearly">
                            <div class="col-md-6">
                                <label for="year" class="form-label">Year</label>
                            </div>
                            <div class="col-md-6">
                                <select id="year" name="year" class="form-select" required>
                                    <?php
                                    // PHP to generate a range of years dynamically
                                    $currentYear = date('Y');
                                    $startYear = 2010;
                                    
                                    for ($year = $currentYear; $year >= $startYear; $year--) {
                                        echo "<option value=\"$year\">$year</option>";
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" form="summaryReportForm" class="btn btn-success"
                            data-bs-dismiss="modal">Generate
                            Report</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {{-- LOADING MODAL  --}}
    <div class="modal fade" id="loadingModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content border-success">
                <div class="modal-body text-center p-4">
                    <div class="text-success mb-3">
                        <i class="fas fa-check-circle fa-3x"></i>
                    </div>
                    <p style="font-size: 1.25em; color: #28a745; font-weight: 500;">
                        Processing your request...
                    </p>
                    <p class="text-muted">
                        Please wait while we process your request. We appreciate your patience!
                    </p>
                    <div class="spinner-border text-success mt-3" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        document.getElementById('periodtype').addEventListener('change', function() {
            const periodType = this.value;
            const periodDuration = document.getElementById('period');
            const ctnPeriodDuration = document.getElementById('periodduration');

            // Clear existing options
            periodDuration.innerHTML = '';

            if (periodType === 'Monthly') {
                ctnPeriodDuration.hidden = false;
                periodDuration.required = true;
                const months = [
                    'January', 'February', 'March', 'April', 'May', 'June',
                    'July', 'August', 'September', 'October', 'November', 'December'
                ];
                months.forEach(month => {
                    const option = document.createElement('option');
                    option.value = month;
                    option.textContent = month;
                    periodDuration.appendChild(option);
                });
            } else if (periodType === 'Quarterly') {
                ctnPeriodDuration.hidden = false;
                periodDuration.required = true;
                const quarters = ['First Quarter', 'Second Quarter', 'Third Quarter', 'Fourth Quarter'];
                quarters.forEach(quarter => {
                    const option = document.createElement('option');
                    option.value = quarter;
                    option.textContent = quarter;
                    periodDuration.appendChild(option);
                });
            } else if (periodType === 'Annually') {
                ctnPeriodDuration.hidden = true;
                periodDuration.required = false;
            }
        });

        // Trigger the change event on page load to populate the default options
        document.getElementById('periodtype').dispatchEvent(new Event('change'));

        $(document).ready(function() {
            function toggleSection(buttonId, containerId) {
                $(buttonId).click(function() {
                    // Fade out all containers, then fade in the selected one
                    $('.ctnreport').not(containerId).hide();
                    $(containerId).fadeIn(400);
                    // Update button classes to reflect active/inactive states
                    $('.reportfilter').not(buttonId).removeClass('btn-success').addClass(
                        'btn-outline-success');
                    $(buttonId).removeClass('btn-outline-success').addClass('btn-success');
                });
            }

            // Attach events to buttons
            toggleSection('#toggleAllReports', '#allReports');
            toggleSection('#toggleCollegeReports', '#collegeReports');
            toggleSection('#toggleSHSReports', '#shsReports');
            toggleSection('#toggleJHSReports', '#jhsReports');
            toggleSection('#toggleElemReports', '#elemReports');
        });

        $(document).ready(function() {
            function toggleSection(buttonId, containerId) {
                $(buttonId).click(function() {
                    // Fade out all containers, then fade in the selected one
                    $('.ctn').not(containerId).hide();
                    $(containerId).fadeIn(400);

                    // Update button classes to reflect active/inactive states
                    $('.filter').not(buttonId).removeClass('btn-success').addClass('btn-outline-success');
                    $(buttonId).removeClass('btn-outline-success').addClass('btn-success');
                });
            }

            // Attach events to buttons
            toggleSection('#toggleCollege', '#college');
            toggleSection('#toggleSHS', '#shs');
            toggleSection('#toggleJHS', '#jhs');
            toggleSection('#toggleElem', '#elem');
        });

        document.addEventListener("DOMContentLoaded", function() {
            // Select the forms
            const summaryReportForm = document.querySelector("#summaryReportForm");
            const reportModal = document.querySelector("#reportModal");
            const perfSummary = document.querySelector("#perfSummary");

            // Function to show the loading modal
            function showLoadingModal(event) {
                const loadingModal = new bootstrap.Modal(document.getElementById('loadingModal'));
                loadingModal.show();
            }

            // Attach event listeners to the forms
            if (summaryReportForm) {
                summaryReportForm.addEventListener("submit", function(event) {
                    showLoadingModal(event);
                });
            }

            if (perfSummary) {
                perfSummary.addEventListener("click", function(event) {
                    showLoadingModal(event);
                });
            }
        });
    </script>
    <script src="{{ asset('js/headercontrol.js') }}"></script>
</body>

</html>
